### ISSUE TITLE
License

### ISSUE THREAD

**Issue by CasimirKaPazi** [BTernaryTau/bternarytau.github.io#3]
Hello. I would like to use an [image in your post](https://bternarytau.github.io/assets/OPOV.png) in the electowiki. But I haven't found a license anywhere.

It would be useful if you add an copyleft license like CC-BY-SA for the blog, or maybe just for that image. Otherwise I will have to recreate it myself.

**Comment by BTernaryTau** [comment]
@CasimirKaPazi I've uploaded an updated version of the image to Electowiki and licensed it appropriately:

https://electowiki.org/wiki/File:One-person-one-vote.png
